In [2]:
%matplotlib inline
import pandas as pd
import os
import time
from Quandl import Quandl
auth_tok = 'aQ5ZPmDWastS5z3yjfvJ'

In [3]:
data = Quandl.get('WIKI/KO', trim_start = '2000-12-12', trim_end = '2014-12-30', authtoken = auth_tok)
data

,Open,High,Low,Close,Volume,Ex-Dividend,Split Ratio,Adj. Open,Adj. High,Adj. Low,Adj. Close,Adj. Volume
Date,,,,,,,,,,,,
2000-12-12,58.31,58.6900,57.6200,58.00,4004100,0.000,1,23.159879,23.310809,22.885821,23.036752,8008200
2000-12-13,58.00,58.3100,57.2500,57.81,3704900,0.000,1,23.036752,23.159879,22.738862,22.961286,7409800
2000-12-14,57.44,57.4400,55.7500,57.00,5023800,0.000,1,22.814328,22.814328,22.143084,22.639566,10047600
2000-12-15,56.69,56.6900,53.5000,53.50,13770200,0.000,1,22.516439,22.516439,21.249417,21.249417,27540400
2000-12-18,53.62,55.5600,53.6200,54.88,5152300,0.000,1,21.297080,22.067619,21.297080,21.797533,10304600
2000-12-19,54.88,57.9400,54.6900,56.75,5844100,0.000,1,21.797533,23.012920,21.722068,22.540270,11688200
2000-12-20,56.75,58.0000,55.5600,56.25,6672100,0.000,1,22.540270,23.036752,22.067619,22.341677,13344200
2000-12-21,56.25,59.6200,56.1200,59.38,5965400,0.000,1,22.341677,23.680192,22.290043,23.584867,11930800
2000-12-22,59.00,59.0000,57.5000,58.88,3741800,0.000,1,23.433937,23.433937,22.838159,23.386275,7483600
2000-12-26,58.88,60.0000,58.6200,60.00,2835000,0.000,1,23.386275,23.831122,23.283006,23.831122,5670000
2000-12-27,60.00,61.3800,60.0000,60.56,3855500,0.000,1,23.831122,24.379238,23.831122,24.053546,7711000
2000-12-28,60.56,61.9400,60.5600,61.06,2760400,0.000,1,24.053546,24.601662,24.053546,24.252139,5520800
2000-12-29,61.06,61.1200,60.1900,60.94,2485200,0.000,1,24.252139,24.275970,23.906587,24.204477,4970400
2001-01-02,60.94,61.9400,60.2500,60.81,5303000,0.000,1,24.204477,24.601662,23.930419,24.152842,10606000
2001-01-03,60.81,62.1900,59.0600,59.25,6234800,0.000,1,24.152842,24.700958,23.457768,23.533233,12469600
2001-01-04,58.88,58.8800,56.7500,57.56,7385300,0.000,1,23.386275,23.386275,22.540270,22.861990,14770600
2001-01-05,57.56,58.7500,57.5000,57.69,3980100,0.000,1,22.861990,23.334641,22.838159,22.913624,7960200
2001-01-08,57.81,59.6900,57.8100,58.62,4764600,0.000,1,22.961286,23.707995,22.961286,23.283006,9529200
2001-01-09,58.62,59.9400,57.6200,59.38,4258100,0.000,1,23.283006,23.807291,22.885821,23.584867,8516200
2001-01-10,59.25,59.2500,57.8800,59.12,3981600,0.000,1,23.533233,23.533233,22.989089,23.481599,7963200
2001-01-11,58.88,58.8800,57.1200,57.38,3454500,0.000,1,23.386275,23.386275,22.687228,22.790497,6909000
2001-01-12,57.38,57.4400,56.2500,56.62,3606000,0.000,1,22.790497,22.814328,22.341677,22.488636,7212000
2001-01-16,56.62,57.3100,56.1900,57.00,3581800,0.000,1,22.488636,22.762694,22.317846,22.639566,7163600
2001-01-17,57.06,58.6900,57.0600,57.94,3825900,0.000,1,22.663397,23.310809,22.663397,23.012920,7651800
2001-01-18,57.94,58.6900,56.9400,57.12,3507200,0.000,1,23.012920,23.310809,22.615735,22.687228,7014400
2001-01-19,57.12,57.1200,55.3100,55.81,4912100,0.000,1,22.687228,22.687228,21.968323,22.166916,9824200
2001-01-22,55.81,56.0600,55.1900,55.69,3437300,0.000,1,22.166916,22.266212,21.920661,22.119253,6874600
2001-01-23,55.69,57.1900,55.4400,56.88,3853900,0.000,1,22.119253,22.715031,22.019957,22.591904,7707800
2001-01-24,56.88,58.0600,56.1200,58.06,4594700,0.000,1,22.591904,23.060583,22.290043,23.060583,9189400
2001-01-25,58.06,59.0000,57.8100,58.62,3743400,0.000,1,23.060583,23.433937,22.961286,23.283006,7486800
...,...,...,...,...,...,...,...,...,...,...,...,...
2014-11-11,42.38,42.7100,42.3600,42.51,8519256,0.000,1,41.409768,41.732213,41.390226,41.536792,8519256
2014-11-12,42.51,42.8900,42.3100,42.71,12767870,0.000,1,41.536792,41.908092,41.341370,41.732213,12767870
2014-11-13,42.65,43.0800,42.6299,42.79,12006900,0.000,1,41.673587,42.093742,41.653947,41.810381,12006900
2014-11-14,42.70,42.9700,42.5000,42.73,10939420,0.000,1,41.722442,41.986261,41.527021,41.751755,10939420
2014-11-17,42.75,42.9900,42.7300,42.92,10647040,0.000,1,41.771297,42.005803,41.751755,41.937405,10647040
2014-11-18,42.99,43.8600,42.7500,43.53,26132605,0.000,1,42.005803,42.855885,41.771297,42.533440,26132605
2014-11-19,43.54,44.4297,43.5600,44.22,25347462,0.000,1,42.543211,43.412543,42.562753,43.207644,25347462
2014-11-20,43.85,44.4200,43.8500,44.25,13462838,0.000,1,42.846114,43.403065,42.846114,43.236957,13462838
2014-11-21,44.58,44.7400,44.2800,44.50,14382570,0.000,1,43.559402,43.715739,43.266270,43.481233,14382570
2014-11-24,44.51,44.7800,44.2000,44.27,12844590,0.000,1,43.491004,43.754823,43.188101,43.256499,12844590
2014-11-25,44.17,44.5900,44.1200,44.43,10728465,0.000,1,43.158788,43.569173,43.109933,43.412836,10728465
2014-11-26,43.98,44.3650,43.9700,44.29,9196101,0.305,1,43.269070,43.647846,43.259231,43.574058,9196101
2014-11-28,44.23,45.0000,44.1500,44.83,10501972,0.000,1,43.515028,44.272581,43.436321,44.105329,10501972
2014-12-01,44.32,44.7650,44.1300,44.55,10052497,0.000,1,43.603573,44.041380,43.416645,43.829856,10052497
2014-12-02,44.38,44.6700,44.2300,44.54,9860626,0.000,1,43.662604,43.947916,43.515028,43.820017,9860626
2014-12-04,43.62,43.8400,43.3700,43.50,13775398,0.000,1,42.914889,43.131333,42.668930,42.796829,13775398
2014-12-05,43.32,43.6100,43.2000,43.53,12525974,0.000,1,42.619738,42.905051,42.501678,42.826344,12525974
2014-12-09,42.31,42.5310,41.6700,42.04,25455917,0.000,1,41.626065,41.843492,40.996410,41.360429,25455917
2014-12-10,42.04,42.2400,41.5600,41.60,18234879,0.000,1,41.360429,41.557196,40.888188,40.927542,18234879
2014-12-11,41.61,42.0100,41.5000,41.53,16168066,0.000,1,40.937380,41.330914,40.829158,40.858673,16168066
2014-12-15,41.10,41.1800,40.5600,40.57,23235600,0.000,1,40.435624,40.514331,39.904353,39.914192,23235600
2014-12-16,40.21,41.3100,39.8000,40.39,23417350,0.000,1,39.560011,40.642230,39.156639,39.737101,23417350
2014-12-17,40.44,41.7600,40.3800,41.55,20175592,0.000,1,39.786293,41.084956,39.727263,40.878350,20175592
2014-12-18,41.86,42.3900,41.7500,42.39,17918113,0.000,1,41.183339,41.704772,41.075117,41.704772,17918113
2014-12-19,42.49,42.7900,41.8900,41.95,23926178,0.000,1,41.803155,42.098306,41.212854,41.271884,23926178
2014-12-22,42.14,42.4400,42.0900,42.35,11131276,0.000,1,41.458813,41.753963,41.409621,41.665418,11131276
2014-12-23,42.54,43.1400,42.4700,42.97,13026464,0.000,1,41.852347,42.442648,41.783478,42.275396,13026464
2014-12-24,43.11,43.2300,42.9200,42.94,6405910,0.000,1,42.413133,42.531193,42.226204,42.245881,6405910
2014-12-26,42.95,43.3000,42.9300,42.96,6365767,0.000,1,42.255719,42.600062,42.236043,42.265558,6365767
2014-12-30,42.72,42.9900,42.6510,42.76,9160093,0.000,1,42.029437,42.295073,41.961553,42.068791,9160093

In [5]:
data.shape

(3528, 12)

In [18]:
path = "intraQuarter/"
def stock_prices():
    df = pd.DataFrame()
    statspath = path+'_KeyStats'
    stock_list = [x[0] for x in os.walk(statspath)]
    for each_dir in stock_list[1:]:
        try:
            ticker = each_dir.split("/")[2]
            print(ticker)
            name = "WIKI/"+ticker.upper()
            data = Quandl.get(name,
                              trim_start = "2000-12-12",
                              trim_end = "2014-12-30",
                              authtoken=auth_tok)
            data[ticker.upper()] = data["Adj. Close"]
            df = pd.concat([df, data[ticker.upper()]], axis = 1)
        except Exception as e:
            print(name,str(e))
            time.sleep(10)
    print(df.head())
    df.to_csv('stock_prices.csv')
stock_prices()

a
aa
aapl
abbv
abc
abt
ace
aci
acn
act
adbe
adi
adm
adp
adsk
adt
aee
aeo
aep
aes
aet
afl
agn
aig
aiv
aiz
akam
all
altr
alxn
amat
amd
amgn
amp
amt
amzn
an
anf
ann
aon

KeyboardInterrupt: